### ISSUE TITLE
Add Support for Python 3.12

### ISSUE THREAD

**Issue by irtazaakram** [openedx/edx-drf-extensions#481]
**Description:**

Follow and complete all of the following steps for the issue to be marked as done.

- [x] Update the `tox.ini`, `setup.py`, `setup.cfg`, or `pyproject.toml` to add Python 3.12 to the supported versions list.
- [x] Ensure GitHub Actions workflows, particularly the CI matrix, reflect Python 3.12 as a supported version.
- [x] Review and adjust any build or testing configurations to ensure compatibility with Python 3.12.
- [x] Run all tests and verify they pass in the CI with Python 3.12.
- [x] Add a CHANGELOG entry: “Added support for Python 3.12.”
- [x] Bump the package version and release a new version on GitHub & PyPI (if applicable).

**Comment by iamsobanjaved** [comment]
PR to drop support for Python 3.8
- https://github.com/openedx/edx-drf-extensions/pull/474

@huniafatima-arbi kindly complete if any item is pending from the checklist otherwise close the issue.
